// LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// CLEAR ERROR
export const CLEAER_ERROR_REQUEST = "CLEAER_REQUEST";
export const CLEAER_ERROR_SUCCESS = "CLEAER_SUCCESS";
export const CLEAER_ERROR_FAILURE = "CLEAER_FAILURE";